[package]
name = "cpu_utils"
version = "0.1.0"
edition = "2021"
authors = ["Muhammad Thariq"]

[dependencies]
common = { path = "../common" }

[lib]
crate-type = ["rlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
